// GENERATED by scratch-l2e-table.mjs — last-two-edges class table.
// classKey (see l2e.js) -> solving token sequence after FR/FL normalization.
export default {
  "0n.1n.1n.0n": [
    "L2",
    "u2",
    "R",
    "F'",
    "U",
    "R'",
    "F",
    "u2"
  ],
  "0f.1f.1f.0f": [
    "L2",
    "u2",
    "R",
    "F'",
    "U",
    "R'",
    "F",
    "u2"
  ],
  "0n.1n.0f.1f": [
    "u'",
    "R",
    "F'",
    "U",
    "R'",
    "F",
    "u"
  ],
  "0n.1f.0f.1n": [
    "u'",
    "R",
    "F'",
    "U",
    "R'",
    "F",
    "u"
  ],
  "0f.1f.0n.1n": [
    "u'",
    "R",
    "F'",
    "U",
    "R'",
    "F",
    "u"
  ],
  "0n.1f.1f.0n": [
    "L2",
    "u2",
    "R",
    "F'",
    "U",
    "R'",
    "F",
    "u2"
  ],
  "0f.1n.0n.1f": [
    "u'",
    "R",
    "F'",
    "U",
    "R'",
    "F",
    "u"
  ],
  "0f.1n.1n.0f": [
    "L2",
    "u2",
    "R",
    "F'",
    "U",
    "R'",
    "F",
    "u2"
  ]
};
