"""Export the trained value net as a base64 Float32 blob for the JS solver."""
import base64, json, sys
from pathlib import Path
import numpy as np

src = Path(sys.argv[1] if len(sys.argv) > 1 else "centers_small.npz")
blob = np.load(src)
keys = sorted(blob.files)
layers, order = [], []
# mlx Linear: y = x @ W.T + b, W is (out, in)
idx = 0
while f"layers.{idx}.weight" in blob:
    order += [f"layers.{idx}.weight", f"layers.{idx}.bias"]
    layers.append(tuple(blob[f"layers.{idx}.weight"].shape))
    idx += 1
order += ["head.weight", "head.bias"]
layers.append(tuple(blob["head.weight"].shape))

flat = np.concatenate([np.asarray(blob[k], dtype=np.float32).ravel() for k in order])
out = Path(__file__).parent.parent / "src" / "solver" / "centers-net.js"
out.write_text(
    "// GENERATED by mlx-solver/export_js.py: do not edit.\n"
    "// Value network for the 4x4 centres, trained by Deep Approximate Value\n"
    "// Iteration. Weights are a base64 Float32 blob in layer order:\n"
    f"// {', '.join(f'{a}x{b}' for a, b in layers)} (+ biases), ReLU between, linear head.\n"
    f"export const SHAPES = {json.dumps(layers)};\n"
    f"export const PARAMS = {len(flat)};\n"
    f"export const WEIGHTS_B64 = '{base64.b64encode(flat.tobytes()).decode()}';\n"
)
print(f"{len(flat):,} params -> {out.name}  ({out.stat().st_size/1024:.0f} KB)")
